### ISSUE TITLE
Time zone is inappropriate

### ISSUE THREAD

**Issue by shaswatam** [fresearchgroup/Collaboration-System#16]
Issue: The time of article creation shown corresponds to the GMT zone and not IST zone.
Priority: Medium

**Comment by fresearchgroup** [comment]
The time zone is set to UTC. https://www.timeanddate.com/time/aboututc.html
This format is followed by many who deal with people across different time zones. edX is one such example. Instead of specifying GMT05:30, we specify UTC. 

Thanks for pointing this issue out. We shall mention that the time is in UTC only

**Comment by shaswatam** [comment]
Thank you for letting me know about the UTC, which I was not aware of.
